#!/usr/bin/python


import random
import sys
sys.path.append("/usr/share/cassandra-tools-wmf")

from cassandra.tools import get_instances


def main(args):
    instance = random.choice(list(get_instances()))
    instance.nodetool.run(*args)

def usage(out):
    print >>out, "Usage: {} <ARG> [ARG ...]\n".format(sys.argv[0])
    print >>out, "Execute nodetool on a randomly selected instance.\n"
    print >>out, "Positional arguments:"
    print >>out, "    ARG    Arguments to pass to nodetool\n"

def get_args():
    if len(sys.argv[1:]) < 1:
        usage(sys.stderr)
        sys.exit(1)
    return sys.argv[1:]


if __name__ == "__main__":
    main(get_args())
