#!/bin/bash

set -e

# If we're running from an uninstalled working-copy, then use the working-copy
# version of the shell include, otherwise assume it is installed.
if [ -r `dirname $0`/functions ]; then
    . `dirname $0`/functions
else
    . /usr/share/cassandra-tools-wmf/functions
fi

ID="$1"
assert_instance_exists "$ID"
shift 1

CONFDIR=`config_directory $ID`
CQLSHRC=${CQLSHRC:-"$CONFDIR"/cqlshrc}

use_ssl()
{
    enabled=`uyaml $CONFDIR/cassandra.yaml /client_encryption_options/enabled`
    optional=`uyaml $CONFDIR/cassandra.yaml /client_encryption_options/optional`
    if test $enabled -gt 0 -a $optional -lt 1; then
        echo "--ssl"
    fi
}


sudo cqlsh --cqlshrc="$CQLSHRC" `use_ssl` `listen_hostname $ID` "$@"
