#!/usr/bin/python


import logging
import sys

from cassandra.tools import get_instances
from cassandra.tools.commands import magenta, cyan, red
from cassandra.tools.nodetool import NodetoolCmdException
from cassandra.tools.config import LOG_LEVEL


logging.basicConfig(level=LOG_LEVEL)


def main():
    for (i, instance) in enumerate(get_instances()):
        color = magenta if (i % 2) == 0 else cyan
        try:
            instance.nodetool.run(*sys.argv[1:], color=color)
        except NodetoolCmdException, err:
            print >>sys.stderr, red(err, True)


if __name__ == "__main__":
    main()
