.\" Hey, EMACS: -*- nroff -*-
.\"
.\" (C) Copyright 2016 Eric Evans <eevans@wikimedia.org>,
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH C-ANY-NT 1 "August 15 2016"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
c-any-nt \- run nodetool commands on a randomly chosen instance
.SH SYNOPSIS
.B c-any-nt <NODETOOL ARGS>
.SH DESCRIPTION
Cassandra environments at the Wikimedia Foundation are able to run an abitrary
number of Cassandra processes on a host. \fBc-any-nt\fP is a program that
runs nodetool commands on any of the configured instances.  It is a convenient
way of running commands when the specific instance does not matter.

.SH EXAMPLES
To see cluster status:
.PP
.nf
    $ c-any-nt status -r
.fi

See the output of \fBnodetool ring\fP:
.PP
.nf
    $ c-any-nt ring
.fi
.SH SEE ALSO
.BR c-ls (1),
.BR c-cqlsh (1),
.BR c-foreach-nt (1),
.BR nodetool (1).
.br
