.\" Hey, EMACS: -*- nroff -*-
.\"
.\" (C) Copyright 2016 Eric Evans <eevans@wikimedia.org>,
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH C-FOREACH-NT 1 "April 26 2016"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
c-foreach-nt \- run nodetool commands iteratively on all instances
.SH SYNOPSIS
.B c-foreach-nt <NODETOOL ARGS>
.SH DESCRIPTION
Cassandra environments at the Wikimedia Foundation are able to run an abitrary
number of Cassandra processes on a host. \fBc-foreach-nt\fP is a program that
runs nodetool commands on each of the enabled instances sequentially.

Output from \fBc-foreach-nt\fP is suffixed with the instance name, and is
printed in alternating colors to help visually discern the output of one
instance from another.
.SH EXAMPLES
To see compaction activity for all instances:
.PP
.nf
    $ c-foreach-nt compactionstats -H
.fi

See the output of \fBnodetool info\fP on all instances:
.PP
.nf
    $ c-foreach-nt info
.fi
.SH SEE ALSO
.BR c-ls (1),
.BR c-cqlsh (1),
.BR nodetool (1).
.br
